project: 
  type: website 
  output-dir: docs 

website:
  title: "Final Project" 
  navbar: 
    left: 
    - Home.qmd
    - Project Details.qmd
    - Final Project.qmd
    - About Us.qmd
   
 
format: 
  html: 
    theme: cosmo 